name: shap_clustering
channels:
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.10.4
  - pip:
      - black==23.3.0
      - isort==5.12.0
      - pytest==7.3.1
      - pytest-cov==4.0.0
      - mypy==1.2.0
      - mypy-extensions==1.0.0
      - types-requests==2.28.11.17
      - taskipy==1.10.4
      - numpy==1.23.5
      - scikit-learn==1.2.2
      - pandas==2.0.0
      - matplotlib==3.7.1
      - seaborn==0.12.2
      - lightgbm==3.3.5
      - llvmlite==0.39.1 
      - numba==0.56.4
      - shap==0.41.0
      - flake8==6.0.0
