name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Define conda environment path as an environment variable
    env:
      CONDAENV: /usr/share/miniconda/envs/shap_clustering/bin


    steps:
      - name: Copy files from repository
        uses: actions/checkout@v3

      - name: Install python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env create --file conda.yaml --name shap_clustering
      
      - name: Run codeing style checks
        run: $CONDAENV/black --check --diff . && $CONDAENV/isort --check --diff . 

      - name: Run linting
        run: $CONDAENV/flake8 . --exit-zero
      
      - name: Run tests
        run: $CONDAENV/pytest -s -x --cov=shap_clustering -vv

      - name: Run coverage xml
        run: $CONDAENV/coverage xml

      - name: Upload coverage xml
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
