name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from repository
        uses: actions/checkout@v3

      - name: Install python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install Poetry
        run: pip install poetry

      - name: Lock poetry
        run: poetry lock

      - name: Install dependencies
        run: poetry install

      - name: Run code standards and tests
        run: poetry run task test --cov-report=xml

